apiVersion: runtime.kwasm.sh/v1alpha1 
kind: Shim
metadata:
  name: spin-v2
  labels:
    app.kubernetes.io/name: spin-v2
    app.kubernetes.io/instance: spin-v2
    app.kubernetes.io/part-of: runtime-class-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: runtime-class-manager
spec:
  nodeSelector:
    spin: "true"

  fetchStrategy:
    type: anonymousHttp
    anonHttp:
      location: "https://github.com/spinkube/containerd-shim-spin/releases/download/v0.14.1/containerd-shim-spin-v2-linux-aarch64.tar.gz"

  runtimeClass:
    name: spin-v2
    handler: spin

  rolloutStrategy:
    type: recreate
