name: CI

on:
  workflow_call:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:
  helm_install_smoke_test:
    uses: ./.github/workflows/helm-chart-smoketest.yml

  helm_node_scaling_test:
    uses: ./.github/workflows/helm-chart-node-scaling-test.yml

  unit_tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26.1"
      - run: make test

  golangci:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26.1"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.11.4
          skip-cache: true
