name: Helm Chart Smoketest

on:
  workflow_call:

env:
  K8S_VERSION: v1.32.3
  MICROK8S_CHANNEL: 1.32/stable
  SHIM_SPIN_VERSION: v0.19.0
  DOCKER_BUILD_SUMMARY: false

jobs:
  build-images:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
          - {
              name: "runtime-class-manager",
              context: ".",
              file: "./Dockerfile"
            }
          - {
              name: "shim-downloader",
              context: "./images/downloader",
              file: "./images/downloader/Dockerfile"
            }
          - {
              name: "node-installer",
              context: ".",
              file: "./images/installer/Dockerfile"
            }
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.config.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.config.context }}
          file: ${{ matrix.config.file }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/${{ matrix.config.name }}.tar
          tags: ${{ matrix.config.name }}:chart-test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.config.name }}
          path: /tmp/${{ matrix.config.name }}.tar

  helm-install-smoke-test:
    runs-on: ubuntu-22.04
    needs: build-images
    strategy:
      matrix:
        config:
          - {
              type: "kind",
              import_cmd: "kind load image-archive"
            }
          - {
              type: "minikube",
              import_cmd: "minikube image load"
            }
          - {
              type: "microk8s",
              import_cmd: "sudo microk8s ctr images import"
            }
          - {
              type: "k3d",
              import_cmd: "k3d image import"
            }

    steps:
      - uses: actions/checkout@v4

      - name: Install helm
        uses: Azure/setup-helm@v4
        with:
          version: v3.17.2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: image-*
          merge-multiple: true
          path: /tmp

      # Note: 'uses' doesn't support variable interpolation, hence the
      # k8s-specific steps below.
      # Ref: https://github.com/orgs/community/discussions/25824
      - name: Create kind cluster
        if: matrix.config.type == 'kind'
        uses: helm/kind-action@v1
        with:
          cluster_name: kind
          # Versions lower than v0.27.0 encounter https://github.com/kubernetes-sigs/kind/issues/3795
          version: v0.27.0
          node_image: kindest/node:${{ env.K8S_VERSION }}

      - name: Create minikube cluster
        if: matrix.config.type == 'minikube'
        run: |
          curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
          install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
          docker build -t minikube-custom:v0.0.46-fixed -f ./images/test/Dockerfile.minikube-custom . --load
          minikube start -p minikube --driver=docker --container-runtime=containerd --base-image="minikube-custom:v0.0.46-fixed" --kubernetes-version=${{ env.K8S_VERSION }}
          kubectl wait pod --all --for=condition=Ready --namespace=kube-system --timeout=180s

      - name: Create microk8s cluster
        if: matrix.config.type == 'microk8s'
        uses: balchua/microk8s-actions@v0.4.3
        with:
          channel: ${{ env.MICROK8S_CHANNEL }}

      - name: Create k3d cluster
        if: matrix.config.type == 'k3d'
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: k3s-default
          k3d-version: v5.8.3
          args: |
            --image docker.io/rancher/k3s:${{ env.K8S_VERSION }}-k3s1

      - name: Import images
        run: |
          for image in $(ls /tmp/*.tar); do
            ${{ matrix.config.import_cmd }} $image
          done

      - name: helm install runtime-class-manager
        run: |
          helm install rcm \
            --namespace rcm \
            --create-namespace \
            --debug \
            --set image.repository=runtime-class-manager \
            --set image.tag=chart-test \
            --set rcm.nodeInstallerImage.repository=node-installer \
            --set rcm.nodeInstallerImage.tag=chart-test \
            --set rcm.shimDownloaderImage.repository=shim-downloader \
            --set rcm.shimDownloaderImage.tag=chart-test \
            deploy/helm

      - name: apply Spin shim
        run: |
          shim_file=config/samples/test_shim_spin.yaml
          if [[ "${{ matrix.config.type }}" == "microk8s" ]]; then
            cp $shim_file config/samples/test_shim_spin_microk8s.yaml
            shim_file=config/samples/test_shim_spin_microk8s.yaml
            # update file to remove the 'containerdRuntimeOptions' field
            # as there is a known bug that MicroK8s containerd does not pass the options
            yq -i 'del(.spec.containerdRuntimeOptions)' $shim_file
          fi
          # Ensure shim binary is compatible with runner arch
          yq -i '.spec.fetchStrategy.anonHttp.location = "https://github.com/spinframework/containerd-shim-spin/releases/download/${{ env.SHIM_SPIN_VERSION }}/containerd-shim-spin-v2-linux-x86_64.tar.gz"' \
            $shim_file
          kubectl apply -f $shim_file

      - name: label nodes
        run: kubectl label node --all spin=true

      - name: verify only one installer pod with Succeeded status
        # TODO: provisioning on k3d still leads to the first installer pod finishing with provisioner status Unknown and phase Failed
        if: matrix.config.type != 'k3d'
        run: |
          timeout 60s bash -c 'until [[ "$(kubectl -n rcm get $(kubectl get pods -n rcm --no-headers -o name | grep install | head -n1) -o jsonpath="{.status.phase}" 2>/dev/null)" == "Succeeded" ]]; do sleep 2; done'

      - name: run Spin App
        run: |
          kubectl apply -f testdata/apps/spin-app.yaml
          kubectl rollout status deployment wasm-spin --timeout 180s
          kubectl get pods -A
          kubectl port-forward svc/wasm-spin 8083:80 &
          timeout 60s bash -c 'until curl -f -vvv http://localhost:8083/hello; do sleep 2; done'

      - name: restart system containerd
        if: matrix.config.type == 'microk8s'
        run: sudo systemctl start containerd

      - name: debug
        if: failure()
        run: |
          kubectl get pods -A
          kubectl describe shim spin-v2
          kubectl describe runtimeclass wasmtime-spin-v2

          # Get install pod logs
          # Note: there may be multiple pods pending k3d fix for issue https://github.com/spinframework/runtime-class-manager/issues/393
          install_pod=$(kubectl get pods -n rcm --no-headers -o name | awk '{if ($1 ~ "-spin-v2-install") print $0}' | tail -n 1)
          kubectl describe -n rcm $install_pod || true
          kubectl logs -n rcm -c downloader $install_pod || true
          kubectl logs -n rcm -c provisioner $install_pod || true

          # RCM pod logs
          kubectl logs -n rcm -l app.kubernetes.io/name=runtime-class-manager || true
          kubectl describe -n rcm pod -l app.kubernetes.io/name=runtime-class-manager || true

          # App logs
          kubectl logs -l app=wasm-spin || true
          kubectl describe pod -l app=wasm-spin || true

      - name: Verify curl
        run: curl localhost:8083/hello
